scripts: run pip with option --quiet to reduce output of upgrade_user_local_bin
Signed-off-by: Stefan Römer <stefan.roemer@senvang.org>

diff --git a/.local/bin/upgrade_user_local_bin b/.local/bin/upgrade_user_local_bin
--- a/.local/bin/upgrade_user_local_bin
+++ b/.local/bin/upgrade_user_local_bin
@@ -55,9 +55,9 @@ if ! [[ -x $(command -v pip) ]]; then
     echo "ERROR: pip required but not available"
     exit 1
 fi
-echo "INFO : installing/upgrading td-watson and nodeenv"
-if ! pip install --upgrade --user pyright nodeenv td-watson pyserial yq khal khard vdirsyncer; then
-    echo "ERROR: installing/upgrading td-watson and nodeenv failed (pip returned $?)"
+echo "INFO : installing/upgrading python tools"
+if ! pip install --quiet --upgrade --user pyright nodeenv td-watson pyserial yq khal khard vdirsyncer; then
+    echo "ERROR: installing/upgrading python tools failed (pip returned $?)"
 else
     echo "INFO : installing/upgrading td-watson and nodeenv finished"
 
